Substructure one Forwarding as a sample
openBackhaul/AutomatedLinkAcceptanceProxy pull request #125
Opened 2023-10-05 08:46 UTC by openBackhaul

2023-10-05 11:25 UTC, vanithavalluripalli9 commented
Hi Thorsten , Thank you for the changes .

Your understanding is correct . The changes we requested are in config file and forwardings.yaml file only.

The changes also looks good . 

Only one small typo mistake , local-id of the forwardings 

- RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole.VlanInterfaceKind
- RequestForProvidingAcceptanceDataCausesDeterminingTheLanPortRole.EthernetContainerStatus

should be "200" in config.json file.

2023-10-05 11:28 UTC, vanithavalluripalli9 requested changes

2023-10-05 11:28 UTC, vanithavalluripalli9 commented on spec/AutomatedLinkAcceptanceProxy+config.json
>                  "local-id": "201",
Can we change the local-id to "200".

2023-10-05 11:28 UTC, vanithavalluripalli9 commented on spec/AutomatedLinkAcceptanceProxy+config.json
>                  "local-id": "202",
can we change local-id to "200"

2023-10-06 06:26 UTC, anacabbar commented on spec/AutomatedLinkAcceptanceProxy+config.json
>                  "local-id": "202",
The local-id has been changed to "200"

2023-10-06 06:26 UTC, anacabbar commented on spec/AutomatedLinkAcceptanceProxy+config.json
>                  "local-id": "201",
The local-id has been changed to "200"

2023-10-09 07:17 UTC, anacabbar commented
The localIds have been corrected and the other Forwardings have been dissolved as proposed

2023-10-09 11:12 UTC, vanithavalluripalli9 approved these changes
Hi Ana, Thank you for the changes .

Changes looks good. Approved the pull request.

2023-10-09 11:13 UTC, merged